import itertools
res=121
results = list(set(int("".join(x)) for x in list(itertools.permutations(list(str(res))))))
results2 = [int("".join(x)) for x in list(itertools.permutations(list(str(res))))]
print(results)
print(results2)
# maximum perfect square of the set of
# permutations generated by the closest
# but higher perfect square than limit_below
